# Usage: brew bundle [install|dump|check|list|cleanup]
# Summary: Install and export a Scoop package manifest, like `brew bundle`.
# Group: lifecycle
# Help: A Brewfile is read line by line. These entries are understood:
#
#   scoop "git"                 a Scoop app
#   brew "git"                  the same, for parity with an existing Brewfile
#   cask "firefox"              a Scoop app from the `extras` bucket
#   bucket "extras"             a Scoop bucket
#   tap "user/repo"             a Scoop bucket named `repo`
#
# Anything else (`mas`, `vscode`, `homebrew_version`, `pre` blocks) is reported
# as skipped. `dump` writes the installed apps and buckets via `scoop export`.
#
#   --file <path>     Use a Brewfile other than ./Brewfile.
#   --force           Overwrite an existing Brewfile during dump; with cleanup,
#                     actually uninstall the extras.
#   --no-install      Only report what would be installed.
param(
    [Parameter(Position = 0)][string]$Subcommand = 'install',
    [string]$File,
    [switch]$Force,
    [switch]$NoInstall,
    [switch]$Describe,
    [Parameter(ValueFromRemainingArguments = $true)][string[]]$Tokens
)

Test-ScoopInstalled | Out-Null

function Get-Brewfile {
    param([string]$Path)

    $candidate = if ($Path) { $Path } else { Join-Path (Get-Location) 'Brewfile' }
    if (-not (Test-Path -LiteralPath $candidate)) { return $null }
    return (Get-Item -LiteralPath $candidate).FullName
}

function Read-Brewfile {
    param([string]$Path)

    $entries = @()
    $skipped = @()
    $lineNumber = 0

    foreach ($line in (Get-Content -LiteralPath $Path)) {
        $lineNumber++
        $text = $line.Trim()
        if (-not $text -or $text.StartsWith('#')) { continue }

        if ($text -match '^(?<type>scoop|brew|cask|bucket|tap)\s+"(?<name>[^"]+)"') {
            $entries += [pscustomobject]@{
                Type = $Matches['type']
                Name = $Matches['name']
                Line = $lineNumber
            }
            continue
        }

        $skipped += [pscustomobject]@{ Line = $lineNumber; Text = $text }
    }

    return [pscustomobject]@{ Entries = $entries; Skipped = $skipped }
}

# Buckets must exist before their packages can resolve.
function Ensure-BrewBuckets {
    param([string[]]$Needed)

    $added = @(Get-BrewBuckets | ForEach-Object { $_.Name })
    foreach ($bucket in ($Needed | Where-Object { $_ } | Select-Object -Unique)) {
        if ($added -contains $bucket) { continue }
        brewMessage "==> Adding bucket '$bucket'"
        $exit = Invoke-Scoop bucket add $bucket
        if ($exit -ne 0) { brewWarn "Could not add bucket '$bucket'." }
        else { Reset-BrewBucketCache; $added += $bucket }
    }
    return $added
}

$bucketsNeeded = @()

switch ($Subcommand) {
    { $_ -in @('dump', 'export') } {
        $target = if ($File) { $File } else { Join-Path (Get-Location) 'Brewfile' }
        if ((Test-Path -LiteralPath $target) -and -not $Force) {
            Abort-Brew "$target already exists. Re-run with --force to overwrite."
        }

        $json = (Invoke-Scoop -Capture export) -join "`n"
        try { $export = $json | ConvertFrom-Json } catch { Abort-Brew 'Could not read `scoop export` output.' }

        $lines = @('# ScoopBrew Brewfile, generated by `brew bundle dump`')
        foreach ($bucket in @($export.buckets)) { $lines += "bucket `"$($bucket.name)`"" }
        if (@($export.buckets).Count -gt 0) { $lines += '' }

        foreach ($app in @($export.apps)) {
            $source = [string]$app.source
            $bucket = if ($source -match '^(?<b>[^/]+)/') { $Matches['b'] } else { 'main' }
            if ($Describe) {
                $pkg = Resolve-BrewPackage $app.name
                if ($pkg -and $pkg.Manifest.description) { $lines += "# $($pkg.Manifest.description)" }
            }
            # Scoop keeps GUI apps in the extras bucket; record them as casks so
            # a re-import adds that bucket before trying to resolve the name.
            if ($bucket -eq 'extras') { $lines += "cask `"$($app.name)`"" }
            else { $lines += "scoop `"$($app.name)`"" }
        }

        Write-BrewTextFile -Path $target -Content $lines
        brewSuccess "Wrote $target ($(@($export.apps).Count) packages)"
        exit 0
    }

    { $_ -in @('install', 'check', 'list') } {
        $brewfile = Get-Brewfile -Path $File
        if (-not $brewfile) {
            Abort-Brew "No Brewfile found at $(if ($File) { $File } else { './Brewfile' }). Generate one with 'brew bundle dump --force'."
        }

        $parsed = Read-Brewfile -Path $brewfile

        foreach ($entry in $parsed.Entries) {
            if ($entry.Type -in @('bucket', 'tap')) { $bucketsNeeded += ($entry.Name -split '/')[-1] }
            if ($entry.Type -eq 'cask') { $bucketsNeeded += 'extras' }
        }
        Ensure-BrewBuckets -Needed $bucketsNeeded | Out-Null

        $installedNames = @(Get-BrewInstalledPackages | ForEach-Object { $_.Name })
        $missing = @()
        $unknown = @()
        foreach ($entry in ($parsed.Entries | Where-Object { $_.Type -in @('scoop', 'brew', 'cask') })) {
            if ($installedNames -contains $entry.Name) { continue }
            if (-not (Resolve-BrewPackage $entry.Name)) { $unknown += $entry; continue }
            $missing += $entry
        }

        if ($Subcommand -eq 'list') {
            foreach ($entry in $parsed.Entries) { Write-Host "$($entry.Type)`t$($entry.Name)" }
            exit 0
        }

        if ($parsed.Skipped.Count -gt 0) {
            foreach ($item in $parsed.Skipped) {
                brewWarn "$brewfile line $($item.Line) is not supported by the Scoop backend: $($item.Text)"
            }
        }

        if ($unknown.Count -gt 0) {
            foreach ($entry in $unknown) {
                brewError "$brewfile line $($entry.Line): no package named '$($entry.Name)' in the added buckets."
            }
            brewMessage ''
            brewMessage "Add the bucket it lives in with 'brew tap <user>/<repo>', or fix the Brewfile."
            exit 1
        }

        if ($missing.Count -eq 0) {
            brewSuccess 'The Brewfile is satisfied: every package is installed.'
            exit 0
        }

        Write-BrewRaw "==> $($missing.Count) package(s) declared but not installed" 'Cyan'
        foreach ($entry in $missing) { brewMessage "  $($entry.Type) `"$($entry.Name)`"" }

        if ($Subcommand -eq 'check' -or $NoInstall) { exit 1 }

        $names = @($missing | ForEach-Object { $_.Name } | Select-Object -Unique)
        brewMessage ''
        brewMessage "==> Installing $($names.Count) package(s)"
        $exit = Invoke-Scoop @(@('install') + $names)
        if ($exit -eq 0) { brewSuccess 'Bundle complete.' }
        exit $exit
    }

    'cleanup' {
        $brewfile = Get-Brewfile -Path $File
        if (-not $brewfile) { Abort-Brew 'No Brewfile found.' }

        $parsed = Read-Brewfile -Path $brewfile
        $declared = @($parsed.Entries | Where-Object { $_.Type -in @('scoop', 'brew', 'cask') } | ForEach-Object { $_.Name })
        $extras = @(Get-BrewInstalledPackages | Where-Object { $declared -notcontains $_.Name })

        if ($extras.Count -eq 0) {
            brewSuccess 'Nothing to remove: every installed package is declared in the Brewfile.'
            exit 0
        }

        Write-BrewRaw "==> $($extras.Count) installed package(s) not in $brewfile" 'Cyan'
        foreach ($entry in $extras) { brewMessage "  $($entry.Name) $($entry.Version)" }

        if (-not $Force) {
            brewMessage ''
            brewMessage 'Nothing was removed. Re-run with --force to uninstall these.'
            exit 1
        }

        exit (Invoke-Scoop @(@('uninstall') + @($extras | ForEach-Object { $_.Name })))
    }

    'exec' {
        Abort-Brew 'brew bundle exec needs a Unix environment to build a PATH; run the program directly, Scoop shims are already on PATH.'
    }

    default {
        Abort-Brew "Unknown brew bundle subcommand: $Subcommand"
    }
}
